name: Build

on: [push, pull_request]

jobs:
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Set up JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 8
          server-id: ossrh
          server-username: SONATYPE_USER
          server-password: SONATYPE_PW

      - name: Build native
        run: |
          cmake -B cmake-build
          cmake --build cmake-build --config Release --verbose --target install

      - name: Build
        run: mvn -B package

      - name: Attach jars
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: target/growl4j-*

      - name: Release to Maven Central
        #if: env.BRANCH == 'master'
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PW: ${{ secrets.SONATYPE_PW }}
        run: |
          cat <(echo -e "${{ secrets.GPG_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
          mvn \
            --no-transfer-progress \
            --batch-mode \
            -Dgpg.passphrase="${{ secrets.GPG_PW }}" \
            -DperformRelease=true \
            deploy
